# -*- coding: utf-8 -*-
"""Copy of car_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c6ZIEG0cLEQpMC3HRI_M18KhqLgkTLPP

Experimenting with:
1. Number of hidden layers in each conv block
2. Varying the values of dropouts
3. THe sizes of the training and testing datasets
4. The number of conv blocks
5. The type of Activation function (relu, gelu, leakyrelu)
6. The number of epochs of training
7, number of classes to be classified
"""

import os
import torch
import torch.nn as nn
from torchvision import transforms
from datasets import load_dataset
from torch.utils.data import DataLoader, Dataset,random_split

# Initialise the DataLoader
from google.colab import drive
drive.mount('./content')

from PIL import Image

class CarDataset(Dataset):

  def __init__(self, root_dir, transform = None):
    self.root_dir = root_dir
    self.transform = transform
    self.imgs = []
    self.labels = []

    for label, class_name in enumerate(os.listdir(root_dir)):
      class_path = os.path.join(root_dir, class_name)
      for img in os.listdir(class_path):
        img_path = os.path.join(class_path, img)
        self.imgs.append(img_path)
        self.labels.append(label)

  def __len__(self):
      return len(self.imgs)

  def __getitem__(self, idx):
    img_path = self.imgs[idx]
    label = self.labels[idx]
    img = Image.open(img_path).convert('RGB')
    if self.transform:
      img = self.transform(img)
    return img,label

from torchvision import transforms

root_dir = './content/MyDrive/CarBodyStyles'

train_transforms = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1),
    transforms.RandomResizedCrop(224, scale=(0.8, 1.0)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

dataset = CarDataset(root_dir, transform=transform)

train_size = int(len(dataset)*0.8)
test_size = len(dataset)-train_size
train_ds, test_ds = random_split(dataset, [train_size, test_size])

train_loader = DataLoader(train_ds, batch_size=32, shuffle=True)
test_loader = DataLoader(test_ds, batch_size=32, shuffle=False)

class ConvBlock(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, pool=True):
        super(ConvBlock, self).__init__()
        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size, stride, padding=1, bias=False)
        self.bn = nn.BatchNorm2d(out_channels)
        self.relu = nn.ReLU(inplace=True)
        self.pool = nn.MaxPool2d(2) if pool else nn.Identity()

    def forward(self, x):
        x = self.conv(x)
        x = self.bn(x)
        x = self.relu(x)
        x = self.pool(x)
        return x

class CarClassifier(nn.Module):

  def __init__(self, num_classes):
    super(CarClassifier, self).__init__()

    self.layer1 = ConvBlock(3,32)
    self.layer2 = ConvBlock(32,64)
    self.layer3 = ConvBlock(64,128)
    self.layer4 = ConvBlock(128,256)
    self.layer5 = ConvBlock(256,512)

    self.gap = nn.AdaptiveAvgPool2d((1,1))
    self.fc1 = nn.Linear(512,256)
    self.drop1 = nn.Dropout(0.5)
    self.fc2 = nn.Linear(256,64)
    self.drop1 = nn.Dropout(0.3)
    self.fc3 = nn.Linear(64, num_classes)
    self.relu = nn.ReLU(inplace = True)

  def forward(self, x, return_features=False):
      features = []

      x = self.layer1(x); features.append(x)
      x = self.layer2(x); features.append(x)
      x = self.layer3(x); features.append(x)
      x = self.layer4(x); features.append(x)
      x = self.layer5(x); features.append(x)

      pooled = self.gap(x)
      flat = torch.flatten(pooled, 1)   #

      x = self.fc1(flat)
      x = self.relu(x)
      x = self.drop1(x)

      x = self.fc2(x)
      x = self.relu(x)
      x = self.drop1(x)

      out = self.fc3(x)

      if return_features:
          return out, features
      return out

device = 'cuda' if torch.cuda.is_available() else 'cpu'
model = CarClassifier(num_classes=2).to(device)

from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

img_path = train_ds.dataset.imgs[0]
img = Image.open(img_path)
img = np.array(img)
plt.imshow(img)

import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-4)

epochs = 25
for epoch in range(epochs):
    model.train()
    total_loss = 0
    correct_predictions = 0
    total_predictions = 0

    for imgs, labels in train_loader:
        imgs, labels = imgs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(imgs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        _, predicted = torch.max(outputs.data, 1)
        total_predictions += labels.size(0)
        correct_predictions += (predicted == labels).sum().item()

    accuracy = 100 * correct_predictions / total_predictions
    print(f"Epoch {epoch+1}/{epochs}, Loss: {total_loss/len(train_loader):.4f}, Accuracy: {accuracy:.2f}%")

model.eval()
img = "/content/test2.avif"
image = Image.open(img).convert('RGB')
input_tensor = transform(image).unsqueeze(0).to(device)

with torch.no_grad():
  output,features = model(input_tensor, return_features = True)

def visualize_features(features, cols=5):
    """
    features: list of feature maps [B, C, H, W]
    """
    for i, fmap in enumerate(features, 1):
        fmap = fmap.detach().cpu()
        num_feat = fmap.shape[1]
        n = min(num_feat, cols)
        fig, axes = plt.subplots(1, n, figsize=(15, 5))
        fig.suptitle(f"Feature Maps After Block {i}", fontsize=16)

        for j in range(n):
            axes[j].imshow(fmap[0, j, :, :], cmap="viridis")
            axes[j].axis("off")

        plt.show()

visualize_features(features)

from google.colab import drive
drive.mount('./content')

import os

# Create folder if it doesn’t exist
model_dir = './content/MyDrive/CarBodyStyles/saved_models'
os.makedirs(model_dir, exist_ok=True)

print("Saving models to:", model_dir)

import os

# Create folder if it doesn’t exist
model_dir = '/content/drive/MyDrive/CarBodyStyles/saved_models'
os.makedirs(model_dir, exist_ok=True)

print("Saving models to:", model_dir)

import torch

save_path = os.path.join(model_dir, 'first_model.pth')
torch.save(model.state_dict(), save_path)

print("Model saved at:", save_path)

import os
import torch

# Correct Google Drive path
model_dir = './content/drive/MyDrive/CarBodyStyles/saved_models'
os.makedirs(model_dir, exist_ok=True)

# Save the model
torch.save(model.state_dict(), os.path.join(model_dir, 'first_model.pth'))

def visualise_contours_edges(img_path):
  img = Image.open(img_path).convert('RGB')
  img = transform(img).unsqueeze(0).to(device)
  model.eval()

  features =

import torch
import torchvision.models as models
import matplotlib.pyplot as plt

model = models.resnet18(pretrained=True)
model.eval()

features = {}

def get_activation(name):
    def hook(model, input, output):
        features[name] = output.detach()
    return hook

model.conv1.register_forward_hook(get_activation('conv1'))
model.layer1[0].conv1.register_forward_hook(get_activation('layer1_conv1'))
model.layer1[0].conv2.register_forward_hook(get_activation('layer1_conv2'))
model.layer2[0].conv1.register_forward_hook(get_activation('layer2_conv1'))

x = transform(Image.open('/content/cconvertible1.jpeg').convert('RGB')).unsqueeze(0)
out = model(x)


act = features['conv1'].squeeze()
fig, axarr = plt.subplots(1, 4, figsize=(12, 6))
for idx in range(4):
    axarr[idx].imshow(act[idx].cpu(), cmap='gray')
    axarr[idx].axis('off')

act2 = features['layer1_conv1'].squeeze()
fig, axarr = plt.subplots(1, 4, figsize=(12, 6))
for idx in range(4):
    axarr[idx].imshow(act2[idx].cpu(), cmap='gray')
    axarr[idx].axis('off')
plt.show()


act3 = features['layer1_conv2'].squeeze()
fig, axarr = plt.subplots(1, 4, figsize=(12, 6))
for idx in range(4):
    axarr[idx].imshow(act3[idx].cpu(), cmap='gray')
    axarr[idx].axis('off')
plt.show()

act4 = features['layer2_conv1'].squeeze()
fig, axarr = plt.subplots(1, 4, figsize=(12, 6))
for idx in range(4):
    axarr[idx].imshow(act4[idx].cpu(), cmap='gray')
    axarr[idx].axis('off')
plt.show()

import torch
import torchvision.models as models
import matplotlib.pyplot as plt
from PIL import Image
from torchvision import transforms

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

model = models.resnet50(pretrained=True)
model.eval()

features = {}

def get_activation(name):
    def hook(model, input, output):
        features[name] = output.detach()
    return hook

layers = [
    ('conv1', model.conv1),

    # --- first 7 ---
    ('layer1_block0_conv1', model.layer1[0].conv1),
    ('layer1_block0_conv2', model.layer1[0].conv2),
    ('layer1_block0_conv3', model.layer1[0].conv3),
    ('layer1_block1_conv1', model.layer1[1].conv1),
    ('layer1_block1_conv2', model.layer1[1].conv2),
    ('layer1_block1_conv3', model.layer1[1].conv3),

    # --- middle 7 ---
    ('layer2_block1_conv1', model.layer2[1].conv1),
    ('layer2_block1_conv2', model.layer2[1].conv2),
    ('layer2_block1_conv3', model.layer2[1].conv3),
    ('layer3_block2_conv1', model.layer3[2].conv1),
    ('layer3_block2_conv2', model.layer3[2].conv2),
    ('layer3_block2_conv3', model.layer3[2].conv3),
    ('layer3_block3_conv1', model.layer3[3].conv1),

    # --- last 7 ---
    ('layer4_block0_conv1', model.layer4[0].conv1),
    ('layer4_block0_conv2', model.layer4[0].conv2),
    ('layer4_block0_conv3', model.layer4[0].conv3),
    ('layer4_block2_conv1', model.layer4[2].conv1),
    ('layer4_block2_conv2', model.layer4[2].conv2),
    ('layer4_block2_conv3', model.layer4[2].conv3),
]

for name, layer in layers:
    layer.register_forward_hook(get_activation(name))

x = transform(Image.open('/content/cconvertible1.jpeg').convert('RGB')).unsqueeze(0)
out = model(x)

def plot_features(name, num_channels=4, cmap='gray'):
    act = features[name].squeeze()
    if act.ndim < 2:  # skip invalid outputs
        print(f"Skipping {name}, invalid shape {act.shape}")
        return
    fig, axarr = plt.subplots(1, num_channels, figsize=(12, 6))
    for idx in range(num_channels):
        axarr[idx].imshow(act[idx].cpu(), cmap=cmap)
        axarr[idx].axis('off')
    plt.suptitle(name)
    plt.show()


for name, _ in layers:
    plot_features(name, num_channels=4, cmap='gray')

import torch
import torchvision.models as models
import torchvision.transforms as transforms
from PIL import Image
import matplotlib.pyplot as plt

model = models.resnet50(pretrained=True)
model.eval()

layers_to_visualize = [
    # first 7 (low-level)
    'conv1', 'bn1', 'relu', 'maxpool',
    'layer1.0.conv1', 'layer1.0.conv2', 'layer1.0.conv3',

    # middle 7 (mid-level)
    'layer2.0.conv1', 'layer2.0.conv2', 'layer2.0.conv3',
    'layer3.0.conv1', 'layer3.0.conv2', 'layer3.0.conv3', 'layer3.1.conv2',

    # last 7 (high-level)
    'layer4.0.conv1', 'layer4.0.conv2', 'layer4.0.conv3',
    'layer4.1.conv1', 'layer4.1.conv2', 'layer4.1.conv3', 'avgpool'
]

features = {}

def get_activation(name):
    def hook(model, input, output):
        features[name] = output.detach()
    return hook

for name, layer in model.named_modules():
    if name in layers_to_visualize:
        layer.register_forward_hook(get_activation(name))

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

img_path = "/content/cconvertible1.jpeg"
img = Image.open(img_path).convert('RGB')
x = transform(img).unsqueeze(0)


with torch.no_grad():
    _ = model(x)

def plot_features(name, num_channels=4, cmap='gray'):
    fmap = features[name].squeeze(0)   # [C,H,W]
    fig, axarr = plt.subplots(1, num_channels, figsize=(15, 5))
    fig.suptitle(f"Feature maps from {name}", fontsize=14)

    for idx in range(num_channels):
        axarr[idx].imshow(fmap[idx].cpu(), cmap=cmap)
        axarr[idx].axis('off')
    plt.show()


for name in layers_to_visualize:
    plot_features(name, num_channels=4, cmap='viridis')

print(model)

!pip install torchsummary

from torchsummary import summary

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

summary(model, (3, 224, 224))